### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by comfortedbasher** [PokemonGo-Enhanced/Enhanced-Backend#2]
stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\denis\Documents\GitHub\PokemonGo-Enhanced\PokemonGo-Enhanced\node_modules\pokemongo-protobuf\node_modules\node-protobuf
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\denis\Documents\GitHub\PokemonGo-Enhanced\PokemonGo-Enhanced\npm-debug.log
C:\Users\denis\Documents\GitHub\PokemonGo-Enhanced\PokemonGo-Enhanced [master ≡ +2 ~0 -0 !]>

**Comment by maxemiliang** [comment]
> stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Have you installed python?

**Comment by comfortedbasher** [comment]
yeah

**Comment by mannie-exe** [comment]
Yo, @comfortedbasher. I have some possible solutions if you're still stuck:

Since you seem to be on Windows...
- Are you using any *Nix-like environments (_Cygwin_, _MinGW_, _WSL_/_Ubuntu_ if Windows 10 Insider), or just native Windows' terminals like _cmd.exe_ or _PowerShell_?
- What's the output of `python --version` in your terminal?

If the output of `python --version` is invalid, you most likely disabled the `Add python.exe to PATH` option during Python's setup:

![Python Installer "Add python.exe to PATH" option](http://jekyll-windows.juthilo.com/public/img/python-path.png)

You can run `for %a in ("%path:;=";"%") do @echo %~a | findstr /l /c:"Python"` just to make sure there are no Python-related entries in your `PATH`. Here are my outputs for the above commands for reference:

``` bat
$ python --version
Python 2.7.12
```

``` bat
$ for %a in ("%path:;=";"%") do @echo %~a | findstr /l /c:"Python"
C:\Development\Python27
C:\Development\Python27\Scripts
```

## Possible Fixes

You can either add the Python root and Scripts directory to your environment via `PATH` or `PYTHON` or just re-install Python with the correct options enabled.

**Comment by jozsi** [comment]
You might also encounter `libprotobuf` problems afterwards, seeing you are on Windows. I've compiled a 64-bit version of it (attached below).
You need to extract it and `SET LIBPROTOBUF=C:\Users\myname\myfolder\extractedlibprotobuf\` before `npm install`.
[protobuf-3.0.0-beta-4-win64.zip](https://github.com/PokemonGo-Enhanced/Enhanced-Backend/files/378869/protobuf-3.0.0-beta-4-win64.zip)

**Comment by nikes** [comment]
```
E:\Go\Enhanced-Backend-master>SET LIBPROTOBUF=C:\libprotobuf

E:\Go\Enhanced-Backend-master>npm install

> node-protobuf@1.3.2 install E:\Go\Enhanced-Backend-master\node_modules\node-protobuf
> node-gyp rebuild


E:\Go\Enhanced-Backend-master\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  init.cpp
  native.cpp
  parse.cpp
  serialize.cpp
..\src\serialize.cpp(37): warning C4244: аргумент: преобразование "double" в "google::protobuf::int64", возможна потеря
 данных [E:\Go\Enhanced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(50): warning C4244: аргумент: преобразование "double" в "google::protobuf::int64", возможна потеря
 данных [E:\Go\Enhanced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(72): warning C4244: аргумент: преобразование "double" в "google::protobuf::uint64", возможна потер
я данных [E:\Go\Enhanced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(85): warning C4244: аргумент: преобразование "double" в "google::protobuf::uint64", возможна потер
я данных [E:\Go\Enhanced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(96): warning C4244: аргумент: преобразование "double" в "float", возможна потеря данных [E:\Go\Enh
anced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(98): warning C4244: аргумент: преобразование "double" в "float", возможна потеря данных [E:\Go\Enh
anced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(39): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных [E:\Go\Enhan
ced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\parse.cpp(144): warning C4267: аргумент: преобразование из "size_t" в "uint32_t"; возможна потеря данных [E:\Go\
Enhanced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\serialize.cpp(207): warning C4267: =: преобразование из "size_t" в "uint32_t"; возможна потеря данных [E:\Go\Enh
anced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(125): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных [E:\Go\Enha
nced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(130): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных [E:\Go\Enha
nced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(168): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных [E:\Go\Enha
nced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
..\src\native.cpp(173): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных [E:\Go\Enha
nced-Backend-master\node_modules\node-protobuf\build\protobuf.vcxproj]
e:\go\enhanced-backend-master\node_modules\nan\nan_new.h(208): warning C4244: аргумент: преобразование "google::protobu
f::int64" в "double", возможна потеря данных (компилируется исходный файл ..\src\parse.cpp) [E:\Go\Enhanced-Backend-mas
ter\node_modules\node-protobuf\build\protobuf.vcxproj]
  ..\src\parse.cpp(60): note: см. ссылку на создание экземпляров функции шаблон при компиляции "v8::Local<v8::Number> N
  an::New<v8::Number,google::protobuf::int64>(A0)"
          with
          [
              A0=google::protobuf::int64
          ]
e:\go\enhanced-backend-master\node_modules\nan\nan_new.h(208): warning C4244: аргумент: преобразование "google::protobu
f::uint64" в "double", возможна потеря данных (компилируется исходный файл ..\src\parse.cpp) [E:\Go\Enhanced-Backend-ma
ster\node_modules\node-protobuf\build\protobuf.vcxproj]
  ..\src\parse.cpp(83): note: см. ссылку на создание экземпляров функции шаблон при компиляции "v8::Local<v8::Number> N
  an::New<v8::Number,google::protobuf::uint64>(A0)"
          with
          [
              A0=google::protobuf::uint64
          ]
  win_delay_load_hook.c
LINK : warning LNK4044: эхЁрёяючэрээ√щ ярЁрьхЄЁ "/LC:\libprotobuf\lib.lib"; шуэюЁшЁєхЄё [E:\Go\Enhanced-Backend-master\
node_modules\node-protobuf\build\protobuf.vcxproj]
C:\Users\Alex\.node-gyp\6.3.0\Release\node.lib : fatal error LNK1127: сшсышюЄхър яютЁхцфхэр [E:\Go\Enhanced-Backend-mas
ter\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\NodeJS\\node.exe" "C:\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Go\Enhanced-Backend-master\node_modules\node-protobuf
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\NodeJS\\node.exe" "C:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Go\Enhanced-Backend-master\npm-debug.log

```

**Comment by jozsi** [comment]
@nikes - unfortunately, I do not understand the error message there. Are you on a 32bit or 64bit windows?

**Comment by nikes** [comment]
64bit

**Comment by AVVS** [comment]
install virtual machine with ubuntu via virtualbox, mount directory as volume and develop like any other developer on *nix machines. windows sucks balls for development.

Full list of shit that you need to install is:
1. visual studio
2. google protobuf
3. node-gyp
4. python
5. rewrite all env variables from unix style to windows style or use cygwin
