### ISSUE TITLE
autoFlick crash

### ISSUE THREAD

**Issue by AVVS** [PokemonGo-Enhanced/Enhanced-Backend#6]
```
TypeError: api.searchPokestop is not a function
  at flickableForts.map.fort (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/lib/mitm/handlers/autoFlick.js:35:55)
  at Array.map (native)
  at safeProcess (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/lib/mitm/handlers/autoFlick.js:35:39)
  at safeProcess (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/lib/utils/safeProcess.js:4:5)
  at mitmServer.addResponseHandler (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/lib/mitm/handlers/autoFlick.js:10:60)
  at PokemonGoMITM.handleResponse (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:194:14)
  at /Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:152:28
  at /Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/http-mitm-proxy/lib/proxy.js:1010:12
  at /Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/async/lib/async.js:181:20
  at Object.async.forEachOf.async.eachOf (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/async/lib/async.js:233:13)
  at Object.async.forEach.async.each (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/async/lib/async.js:209:22)
  at Proxy._onResponseEnd (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/http-mitm-proxy/lib/proxy.js:1009:9)
  at end (/Users/vitaly/projects/Pokemon-Enhanced/Enhanced-Backend/node_modules/http-mitm-proxy/lib/proxy.js:846:20)
  at Gunzip.onend (_stream_readable.js:512:10)
  at Gunzip.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Gunzip.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:975:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by jozsi** [comment]
Fixed via a174cab083ecd5e35ec1f85f454fe2b38bee3c97
