### ISSUE TITLE
Start problem

### ISSUE THREAD

**Issue by nikes** [PokemonGo-Enhanced/Enhanced-Backend#7]
```
E:\Go\Enhanced-Backend-master>node lib/server.js
E:\Go\Enhanced-Backend-master\lib\express\routes\index.js:17
  let pokemons = req.app.locals.pokemons;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Go\Enhanced-Backend-master\lib\express\setup.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

E:\Go\Enhanced-Backend-master>node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'E:\Go\Enhanced-Backend-master\index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

All modules installed

**Comment by rubenvereecken** [comment]
We're under such heavy development things keep changing all the time (_frowns at @AVVS_).

Try `npm run dev`.

**Comment by nikes** [comment]
i started this at windows 

```
E:\Go\Enhanced-Backend-master>npm run dev

> pokemongo-enhanced@1.0.0 dev E:\Go\Enhanced-Backend-master
> DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js

"DEBUG" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\NodeJS\\node.exe" "C:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! pokemongo-enhanced@1.0.0 dev: `DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemongo-enhanced@1.0.0 dev script 'DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js'.
npm ERR! This is most likely a problem with the pokemongo-enhanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemongo-enhanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pokemongo-enhanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Go\Enhanced-Backend-master\npm-debug.log
```

**Comment by rubenvereecken** [comment]
```
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
```

Install the appropriate Node version as explained in the README please

**Comment by nikes** [comment]
```
E:\Go\Enhanced-Backend-master>npm run dev

> pokemongo-enhanced@1.0.0 dev E:\Go\Enhanced-Backend-master
> DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js

"DEBUG" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\NodeJS\\node.exe" "C:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pokemongo-enhanced@1.0.0 dev: `DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemongo-enhanced@1.0.0 dev script 'DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemongo-enhanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemongo-enhanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemongo-enhanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Go\Enhanced-Backend-master\npm-debug.log
```

...
fix it
in cmd
`set DEBUG=mitm:*,enhanced:*`
next
`node`
next
`nodemon ./lib/server.js`
and i see 3 dot it normal?

**Comment by jozsi** [comment]
I have fixed the `npm start` and `npm run dev` commands to be cross-platform compatible via 1e9bc2e7391bc041ae26ec4da77a0c68b3d92b66 (indeed, they didn't work on windows)

@nikes - if you see any other issues, please re-open the issue.
