### ISSUE TITLE
Cannot run npm run dev  (OS: raspberry pi ubuntu mate)

### ISSUE THREAD

**Issue by Kurainu** [PokemonGo-Enhanced/Enhanced-Backend#8]
julian@julian-desktop:~/Schreibtisch/Pokemon-stuff/Enhanced-Backend$ sudo npm run dev
[sudo] password for julian: 

> pokemongo-enhanced@1.0.0 dev /home/julian/Schreibtisch/Pokemon-stuff/Enhanced-Backend
> cross-env DEBUG=mitm:_,enhanced:_ nodemon ./lib/server.js

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: _._
[nodemon] starting `node ./lib/server.js`
/home/julian/Schreibtisch/Pokemon-stuff/Enhanced-Backend/lib/express/routes/index.js:17
  let pokemons = req.app.locals.pokemons;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/julian/Schreibtisch/Pokemon-stuff/Enhanced-Backend/lib/express/setup.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by AVVS** [comment]
install node 6.3.1

**Comment by jozsi** [comment]
You are using Node v4 instead of the required v6 (as described in the [requirements](https://github.com/PokemonGo-Enhanced/Enhanced-Backend#requirements)).
