### ISSUE TITLE
unable to find certificate

### ISSUE THREAD

**Issue by itzyosh** [PokemonGo-Enhanced/Enhanced-Backend#9]
Got it to run fine but i am unable to find the certificate.

Running ubuntu

**Was looking in the wrong places found it**

**Comment by rubenvereecken** [comment]
I assume you found it :)?

**Comment by itzyosh** [comment]
That I did.  Ran into some more problems, no time to troubleshoot tonight.  Will reopen if need be

**Comment by jozsi** [comment]
As a side nide, the certificates folder is prefixed with `.`, so it's a hidden folder on Mac OS X and Linux. You need to `ls -al` in the Terminal to see it.

**Comment by itzyosh** [comment]
Not sure exactly what is wrong. once i open app this shows up. Ive been away from code for a few years. POGO re sparked my interest not sure what is happening here 

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/yosh/.nvm/versions/node/v6.3.1/bin/node',
1 verbose cli   '/home/yosh/.nvm/versions/node/v6.3.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle pokemongo-enhanced@1.0.0~predev: pokemongo-enhanced@1.0.0
6 silly lifecycle pokemongo-enhanced@1.0.0~predev: no script for predev, continuing
7 info lifecycle pokemongo-enhanced@1.0.0~dev: pokemongo-enhanced@1.0.0
8 verbose lifecycle pokemongo-enhanced@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle pokemongo-enhanced@1.0.0~dev: PATH: /home/yosh/.nvm/versions/node/v6.3.1/lib/node_modules/npm/bin/node-gyp-bin:/home/yosh/PokemonGo-Enhanced/node_modules/.bin:/home/yosh/.nvm/versions/node/v6.3.1/bin:/home/yosh/.nvm/versions/node/v6.3.1/bin:/home/yosh/bin:/home/yosh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle pokemongo-enhanced@1.0.0~dev: CWD: /home/yosh/PokemonGo-Enhanced
11 silly lifecycle pokemongo-enhanced@1.0.0~dev: Args: [ '-c',
11 silly lifecycle   'cross-env DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js' ]
12 silly lifecycle pokemongo-enhanced@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle pokemongo-enhanced@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: pokemongo-enhanced@1.0.0 dev: `cross-env DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/yosh/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/yosh/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pokemongo-enhanced@1.0.0
16 verbose cwd /home/yosh/PokemonGo-Enhanced
17 error Linux 4.4.0-31-generic
18 error argv "/home/yosh/.nvm/versions/node/v6.3.1/bin/node" "/home/yosh/.nvm/versions/node/v6.3.1/bin/npm" "run" "dev"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error pokemongo-enhanced@1.0.0 dev: `cross-env DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js`
22 error Exit status 1
23 error Failed at the pokemongo-enhanced@1.0.0 dev script 'cross-env DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pokemongo-enhanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env DEBUG=mitm:*,enhanced:* nodemon ./lib/server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pokemongo-enhanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pokemongo-enhanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jozsi** [comment]
Are you running node v6?

**Comment by itzyosh** [comment]
front and backend seem to be working. but once i go localhost comes up not found
